logrotate.conf: rotate under "adm" group, not root
This gets rid of massive warning spam from the script like this:

    error: skipping "/var/log/apache2/access.log" because parent
    directory has insecure permissions (It's world writable or
    writable by group which is not "root") Set "su" directive in
    config file to tell logrotate which user/group should be used for
    rotation.